apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent2
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: zabbix-agent2
  template:
    metadata:
      labels:
        app: zabbix-agent2
    spec:
      containers:
      - name: zabbix-agent2
        image: zabbix/zabbix-agent2:latest
        env:
        - name: ZBX_SERVER_HOST
          value: "15.207.98.162" # Name of the Zabbix Proxy
        - name: ZBX_SERVER_PORT
          value: "10051"
        - name: ZBX_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: host-root
          mountPath: /host-root
          readOnly: true
        securityContext:
          privileged: true
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory
