apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-proxy-config
  namespace: zabbix
data:
  zabbix_proxy.conf: |
    Server=3.110.119.153
    Hostname=zabbix-proxy
    LogFile=/var/log/zabbix/zabbix_proxy.log
    DBName=/var/lib/zabbix/zabbix_proxy.db
    ConfigFrequency=3600
    DataSenderFrequency=1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-proxy
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-proxy
  template:
    metadata:
      labels:
        app: zabbix-proxy
    spec:
      containers:
      - name: zabbix-proxy
        image: zabbix/zabbix-proxy-sqlite3:6.0-latest
        ports:
        - containerPort: 10051
        volumeMounts:
        - name: zabbix-proxy-config
          mountPath: /etc/zabbix/zabbix_proxy.conf
          subPath: zabbix_proxy.conf
      volumes:
      - name: zabbix-proxy-config
        configMap:
          name: zabbix-proxy-config
